Add ilike pushdown function for tiflash
pingcap/docs pull request #12928
Opened 2023-03-16 06:45 UTC by xzhangxian1008

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [ ] master (the latest development version)
- [ ] v7.0 (TiDB 7.0 versions)
- [ ] v6.6 (TiDB 6.6 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.4 (TiDB 6.4 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2023-03-16 09:33 UTC, dveeden requested changes
I don't see an `Ilike` (or `ILIKE`) on https://docs.pingcap.com/tidb/dev/operators

It also doesn't seem to be present in the last nightly build:
```
sql> SELECT "FOO" LIKE "FOO";
+------------------+
| "FOO" LIKE "FOO" |
+------------------+
|                1 |
+------------------+
1 row in set (0.0015 sec)

sql> SELECT "FOO" RLIKE "FOO";
+-------------------+
| "FOO" RLIKE "FOO" |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.0012 sec)

sql> SELECT "FOO" ILIKE "FOO";
ERROR: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 24 near ""FOO"" 

sql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: ee7c089e55e6d95425c745c8a9073632aa5e760e
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-15 14:34:49
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.0011 sec)
```

Could you fill in more of the pull request template with background on this and references?

2023-03-17 06:46 UTC, xzhangxian1008 commented
> I don't see an `Ilike` (or `ILIKE`) on https://docs.pingcap.com/tidb/dev/operators
> 
> It also doesn't seem to be present in the last nightly build:
> 
> ```
> sql> SELECT "FOO" LIKE "FOO";
> +------------------+
> | "FOO" LIKE "FOO" |
> +------------------+
> |                1 |
> +------------------+
> 1 row in set (0.0015 sec)
> 
> sql> SELECT "FOO" RLIKE "FOO";
> +-------------------+
> | "FOO" RLIKE "FOO" |
> +-------------------+
> |                 1 |
> +-------------------+
> 1 row in set (0.0012 sec)
> 
> sql> SELECT "FOO" ILIKE "FOO";
> ERROR: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 24 near ""FOO"" 
> 
> sql> SELECT tidb_version()\G
> *************************** 1. row ***************************
> tidb_version(): Release Version: v6.7.0-alpha
> Edition: Community
> Git Commit Hash: ee7c089e55e6d95425c745c8a9073632aa5e760e
> Git Branch: heads/refs/tags/v6.7.0-alpha
> UTC Build Time: 2023-03-15 14:34:49
> GoVersion: go1.20.2
> Race Enabled: false
> TiKV Min Version: 6.2.0-alpha
> Check Table Before Drop: false
> Store: tikv
> 1 row in set (0.0011 sec)
> ```
> 
> Could you fill in more of the pull request template with background on this and references?

ilike function was just merged into tidb. [pr](https://github.com/pingcap/tidb/pull/40942)

2023-03-17 07:55 UTC, dveeden requested changes
This also needs to be added to `functions-and-operators/operators.md`.

Make sure to add a `## MySQL compatibility` section as `ILIKE` doesn't exist in MySQL and is also not in the SQL standards.

2023-03-17 07:55 UTC, dveeden commented on tiflash/tiflash-supported-pushdown-calculations.md
> +| [Logical functions](/functions-and-operators/control-flow-functions.md) and [operators](/functions-and-operators/operators.md) | `AND`, `OR`, `NOT`, `CASE WHEN`, `IF()`, `IFNULL()`, `ISNULL()`, `IN
```suggestion
| [Logical functions](/functions-and-operators/control-flow-functions.md) and [operators](/functions-and-operators/operators.md) | `AND`, `OR`, `NOT`, `CASE WHEN`, `IF()`, `IFNULL()`, `ISNULL()`, `IN`, `LIKE`, `ILIKE`, `COALESCE`, `IS` |
```

2023-04-03 07:37 UTC, joey-yez commented on tiflash/tiflash-supported-pushdown-calculations.md
> +| [Logical functions](/functions-and-operators/control-flow-functions.md) and [operators](/functions-and-operators/operators.md) | `AND`, `OR`, `NOT`, `CASE WHEN`, `IF()`, `IFNULL()`, `ISNULL()`, `IN
```suggestion
| [Logical functions](/functions-and-operators/control-flow-functions.md) and [operators](/functions-and-operators/operators.md) | `AND`, `OR`, `NOT`, `CASE WHEN`, `IF()`, `IFNULL()`, `ISNULL()`, `IN`, `LIKE`, `ILIKE`, `COALESCE`, `IS` |
```

2023-04-03 08:43 UTC, xzhangxian1008 commented
> This also needs to be added to `functions-and-operators/operators.md`.
> 
> Make sure to add a `## MySQL compatibility` section as `ILIKE` doesn't exist in MySQL and is also not in the SQL standards.
> 
> You might want to link to https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html
> 
> An example for how MySQL does this:
> 
> ```
> mysql> WITH a AS (SELECT "foo" c1 UNION ALL SELECT "FOO") SELECT c1, c1 = "foo", c1 LIKE "foo", c1 LIKE "foo" COLLATE utf8mb4_0900_as_cs FROM a;
> +-----+------------+---------------+------------------------------------------+
> | c1  | c1 = "foo" | c1 LIKE "foo" | c1 LIKE "foo" COLLATE utf8mb4_0900_as_cs |
> +-----+------------+---------------+------------------------------------------+
> | foo |          1 |             1 |                                        1 |
> | FOO |          1 |             1 |                                        0 |
> +-----+------------+---------------+------------------------------------------+
> 2 rows in set (0.00 sec)
> 
> mysql> WITH a AS (SELECT "foo" COLLATE utf8mb4_0900_as_cs c1 UNION ALL SELECT "FOO") SELECT c1, c1 = "foo", c1 LIKE "foo", c1 LIKE "foo" COLLATE utf8mb4_0900_
> +------+------------+---------------+------------------------------------------+
> | c1   | c1 = "foo" | c1 LIKE "foo" | c1 LIKE "foo" COLLATE utf8mb4_0900_as_cs |
> +------+------------+---------------+------------------------------------------+
> | foo  |          1 |             1 |                                        1 |
> | FOO  |          0 |             0 |                                        0 |
> +------+------------+---------------+------------------------------------------+
> 2 rows in set (0.01 sec)
> 
> mysql> SELECT VERSION();
> +-----------+
> | VERSION() |
> +-----------+
> | 8.0.32    |
> +-----------+
> 1 row in set (0.00 sec)
> ```
> 
> Maybe discuss with the documentation team if we want to document this as PostgreSQL compatibility? If we do, maybe link to https://www.postgresql.org/docs/current/functions-matching.html
> 
> Also looks like Snowflake has this as well: https://docs.snowflake.com/en/sql-reference/functions/ilike

okk

2023-04-03 10:06 UTC, qiancai commented on functions-and-operators/operators.md
> +| [ILIKE](https://www.postgresql.org/docs/current/functions-matching.html) | Simple pattern matching with case insensitive(Supported in TiDB, but not supported in MySQL) |
```suggestion
| [ILIKE](https://www.postgresql.org/docs/current/functions-matching.html) | Simple pattern matching with case insensitive (Supported in TiDB, but not supported in MySQL) |
```

2023-04-03 10:06 UTC, qiancai commented on functions-and-operators/operators.md
> +| [ILIKE](https://www.postgresql.org/docs/current/functions-matching.html) | Simple pattern matching with case insensitive(Supported in TiDB, but not supported in MySQL) |
```suggestion
| [ILIKE](https://www.postgresql.org/docs/current/functions-matching.html) | Simple pattern matching with case insensitive (Supported in TiDB, but not supported in MySQL) |
```

2023-04-03 13:01 UTC, dveeden approved these changes

2023-04-07 02:03 UTC, qiancai approved these changes

2023-04-07 02:08 UTC, ran-huang approved these changes

2023-04-07 02:10 UTC, qiancai commented
/merge

2023-04-07 02:10 UTC, merged