Update partitioned-table.md
pingcap/docs pull request #16123
Opened 2024-01-11 10:17 UTC by hey-hoho

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
fix #10817 

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [x] v7.6 (TiDB 7.6 versions)
- [x] v7.5 (TiDB 7.5 versions)
- [x] v7.4 (TiDB 7.4 versions)
- [x] v7.3 (TiDB 7.3 versions)
- [x] v7.1 (TiDB 7.1 versions)
- [x] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-01-11 10:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/docs?pullRequest=16123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/docs?pullRequest=16123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/docs?pullRequest=16123) it.</sub>

2024-01-11 10:20 UTC, dveeden commented on partitioned-table.md
> +- For `RANGE COLUMNS`, only one column that is integer, date, and datetime types is supported as partitioning key.
```suggestion
- For `RANGE COLUMNS`, only one column that is an integer, date, and datetime types is supported as partitioning key.
```

2024-01-18 15:43 UTC, qiancai commented on partitioned-table.md
> +- For `RANGE COLUMNS`, only one column that is an integer, date, or datetime types is supported as partitioning key.
```suggestion
- For `RANGE COLUMNS` partitioning, only one column that is in the integer, date, or datetime type can be used as the partitioning key.
```

2024-01-18 15:43 UTC, qiancai commented on partitioned-table.md
Besides L298, please also update the L172 to fix the issue:

![image](https://github.com/pingcap/docs/assets/79440533/297b558c-0627-4785-a7e1-b488c87471cf)

2024-01-19 04:09 UTC, hey-hoho commented on partitioned-table.md
range column partitioning can use mutilple columns, but it cannot be used together with range interval partitioning
.

2024-01-19 09:02 UTC, qiancai commented on partitioned-table.md
yes, you're right.👍 Thanks for the explaination.

2024-01-19 09:11 UTC, qiancai commented on partitioned-table.md
> +- For `RANGE COLUMNS` partitioning, only one column that is in the integer, date, or datetime type can be used as the partitioning key.
```suggestion
- If you want to use the `INTERVAL` syntax for `RANGE COLUMNS` partitioning, only one column that is in the integer, date, or datetime type can be specified as the partitioning key.
```

2024-01-19 09:44 UTC, mjonss commented
This should not be added to v6.5 or later, since it was added in 6.5. v6.1 does support single column RANGE COLUMNS partitioning, but it does not seem to be documented (also not sure if it was considered GA or not in v6.1). Looking at the first PR, https://github.com/pingcap/docs/pull/10819, it was proposed only for v6.3/v6.4, so I assume RANGE COLUMNS was not considered GA in v6.1.

So unless we update v6.1, I think we can close this pr and the associated bug instead.

2024-01-19 09:46 UTC, mjonss requested changes
I made a mistake, not taking the INTERVAL part into account, only the RANGE COLUMNS multi-columns one.
~~Multi-column RANGE COLUMN is supported since v6.5, so please consider [this comment](https://github.com/pingcap/docs/pull/16123#issuecomment-1900075811).~~

2024-01-19 09:55 UTC, mjonss commented
Multi-column RANGE COLUMNs was added in v6.3, so the single column RANGE COLUMNs docs update would only apply to v6.1, which don't even mention RANGE COLUMN, so I think it is safe to close this PR and [issue](https://github.com/pingcap/docs/issues/10817).

2024-01-19 16:04 UTC, qiancai commented
It seems that [INTERVAL partitioning does not support multi-column RANGE COLUMNS partitioning · Issue #10817 · pingcap/docs](https://github.com/pingcap/docs/issues/10817) was reported after the following two v6.3 PRs are merged:

- [table partition: add INTERVAL partitioning by mjonss · Pull Request #9751 · pingcap/docs](https://github.com/pingcap/docs/pull/9751)
- [table partition: add RANGE COLUMNS partitioning by mjonss · Pull Request #10385 · pingcap/docs](https://github.com/pingcap/docs/pull/10385)

2024-01-19 19:11 UTC, mjonss approved these changes
LGTM, with the suggestion from @qiancai.
Sorry I previously missed the INTERVAL part of the issue.

2024-01-23 08:01 UTC, qiancai commented on partitioned-table.md
> +- If you want to use the `INTERVAL` syntax for `RANGE COLUMNS` partitioning, only one column that is in the integer, date, or datetime type can be specified as the partitioning key.
```suggestion
- If you want to use the `INTERVAL` syntax for `RANGE COLUMNS` partitioning, only a single column that is in the integer, date, or datetime type can be specified as the partitioning key.
```

2024-01-23 08:16 UTC, hfxsd commented on partitioned-table.md
> +- If you want to use the `INTERVAL` syntax for `RANGE COLUMNS` partitioning, only a single column that is in the integer, date, or datetime type can be specified as the partitioning key.
```suggestion
- If you want to use the `INTERVAL` syntax for `RANGE COLUMNS` partitioning, you can only specify a single column that is in the `INTEGER`, `DATE`, or `DATETIME` type as the partitioning key.
```

2024-01-23 08:41 UTC, qiancai commented
/approve

2024-01-23 08:42 UTC, merged