Update tidb-roadmap.md
pingcap/docs pull request #19350
Opened 2024-11-06 14:23 UTC by Frank945946

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Updated the TiDB RoadMap
 

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [ ] master (the latest development version)
- [ ] v8.5 (TiDB 8.5 versions)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-11-14 01:54 UTC, hfxsd commented on tidb-roadmap.md
> +            <br />Reduces recovery time for full database and point-in-time restores (PITR).
```suggestion
            <br />Reduces recovery time for full database and Point in Time Recovery (PITR).
```

2024-11-14 07:59 UTC, joey-yez approved these changes

2024-11-20 04:52 UTC, alastori requested changes

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Allows operators like HashAgg, Sort, and Join to spill to disk, reducing memory load and preventing out-of-memory (OOM) issues.
```suggestion
            <br />Allows operators such as HashAgg, Sort, and Join to spill to disk, reducing memory load and preventing out-of-memory (OOM) issues.
```

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Monitors memory usage across all components to prevent operations that might impact system stability.
```suggestion
            <br />Monitors memory usage across all components to prevent operations that might affect system stability.
```

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <b>Permissioned Resource Group Switching (GA)</b>
```suggestion
            <b>Access Control for Resource Group Switching (GA)</b>
```

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Allows tailored statistics strategies for specific tables, adjusting parameters like health and parallelism.
```suggestion
            <br />Allows tailored statistics strategies for specific tables, adjusting parameters such as health and concurrency.
```

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Establishes a unified SQL execution time model to help identify database load sources through logs and cluster metrics, pinpointing problematic nodes and statements.
```suggestion
            <br />Establishes a unified SQL execution time model to help identify database load sources through statement summary tables, logs, and cluster metrics, pinpointing problematic nodes and statements.
```

2024-11-23 03:24 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Adds TiFlash CPU time metrics to statements and slow logs, enabling quick identification of statements that cause CPU spikes in TiFlash.
```suggestion
            <br />Adds TiFlash CPU time metrics to statement summary tables and slow logs, enabling quick identification of statements that cause CPU spikes in TiFlash.
```

2024-11-24 06:04 UTC, qiancai reviewed
Rest LGTM

2024-11-25 08:40 UTC, niubell commented on tidb-roadmap.md
> +            <br />Migrate region meta storage from PD to TiKV, allowing the storage layer to scale infinitely and easily.
Split a dedicated stateless Router Service(Read/Write of region metadata), and migrate region metadata storage from PD to TiKV, the metadata storage layer will scale limitless and easily.

2024-11-25 08:58 UTC, hfxsd commented on tidb-roadmap.md
> +            <br />Migrate region meta storage from PD to TiKV, allowing the storage layer to scale infinitely and easily.
```suggestion
            <br />Splits a dedicated stateless Router Service (Read/Write of region metadata), and migrates region metadata storage from PD to TiKV. The metadata storage layer will scale limitless and easily.
```

2024-11-25 15:00 UTC, hfxsd approved these changes

2024-11-26 00:24 UTC, alastori approved these changes

2024-11-26 01:09 UTC, hfxsd commented
/retest

2024-11-26 01:43 UTC, qiancai approved these changes
Rest LGTM

2024-11-26 01:43 UTC, qiancai commented on tidb-roadmap.md
> +            <br />Splits a dedicated stateless Router Service (Read/Write of region metadata), and migrates region metadata storage from PD to TiKV. The metadata storage layer will scale limitless an
```suggestion
            <br />Splits a dedicated stateless router service (read/write of region metadata) and migrates region metadata storage from PD to TiKV. The metadata storage layer will scale limitlessly and easily.
```

2024-11-26 01:57 UTC, hfxsd commented
/retest

2024-11-26 02:04 UTC, hfxsd commented
/retest

2024-11-26 02:25 UTC, hfxsd commented
/approve

2024-11-26 02:27 UTC, merged