toc: reorganize TiCDC docs in left navigation
pingcap/docs pull request #19365
Opened 2024-11-08 06:49 UTC by lilin90

### What is changed, added or deleted? (Required)

- Moves TiCDC docs from **TiDB Tools** > [**TiCDC**](https://docs.pingcap.com/tidb/dev/ticdc-overview) to the first level in left navigation, to make it easier to find
- Renames TiCDC to **Stream Data** in the left navigation
- Combines the exiting first-level [**Integrate**](https://docs.pingcap.com/tidb/dev/integration-overview) with the TiCDC docs

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [x] master (the latest development version)
- [ ] v8.5 (TiDB 8.5 versions)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-11-13 07:58 UTC, Oreoxmt commented on TOC.md
> +  - Changefeeds
```suggestion
  - Changefeed
```

2024-11-13 08:10 UTC, Oreoxmt approved these changes

2024-11-13 19:31 UTC, benmeadowcroft requested changes

2024-11-13 19:31 UTC, benmeadowcroft commented on TOC.md
> +  - Integrate
I think "Integration Scenarios" would explain this section better

2024-11-13 19:31 UTC, benmeadowcroft commented on TOC.md
> +    - [TiCDC Client Authentication](/ticdc/ticdc-client-authentication.md)
This is not changefeed specific so should be in the Reference section

2024-11-13 19:31 UTC, benmeadowcroft commented on TOC.md
> +    - [Data Integrity Validation for Single-Row Data](/ticdc/ticdc-integrity-check.md)
I think this is a good candidate for the Reference section

2024-11-13 19:31 UTC, benmeadowcroft commented on TOC.md
> +    - [Data Consistency Validation for TiDB Upstream/Downstream Clusters](/ticdc/ticdc-upstream-downstream-check.md)
I think this is a good candidate for the Reference section

2024-11-13 19:31 UTC, benmeadowcroft commented on TOC.md
> +    - [TiCDC Behavior in Splitting UPDATE Events](/ticdc/ticdc-split-update-behavior.md)
I think this is a good candidate for the Reference section

2024-11-14 06:24 UTC, lilin90 commented
@benmeadowcroft Thanks for your suggestions! All the suggestions have been accepted via https://github.com/pingcap/docs/pull/19365/commits/648fd005b35c3ce1f0b2d659c9649c46d2d96ef6.

2024-11-19 02:36 UTC, benmeadowcroft approved these changes

2024-11-19 08:19 UTC, lilin90 commented
/approve

2024-11-19 08:34 UTC, merged