Add document for tiup cluster clean
pingcap/docs pull request #3724
Opened 2020-08-25 04:21 UTC by Joyinqin

### What is changed, added or deleted? (Required)
Add document for tiup cluster clean

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/4233
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

2020-08-25 04:23 UTC, Joyinqin commented
/label needs-cherry-pick-4.0, size/small, status/PTAL, translation/from-docs-cn

2020-08-25 04:24 UTC, Joyinqin commented
/cc lucklove, TomShawn

2020-08-25 04:48 UTC, Joyinqin commented
/uncc lucklove, TomShawn

2020-08-26 11:07 UTC, Joyinqin commented
/cc lucklove, TomShawn

2020-08-26 11:09 UTC, TomShawn commented
@lilin90 Please help review this PR, thanks!

2020-08-26 11:10 UTC, lucklove approved these changes
LGTM

2020-08-27 09:42 UTC, lilin90 requested changes

2020-08-27 09:42 UTC, lilin90 commented on maintain-tidb-using-tiup.md
> +- Clean up the logs and data of all services except the node `172.16.13.11:9000`:
```suggestion
- Clean up the logs and data of all services except the `172.16.13.11:9000` instance:
```

2020-08-27 09:42 UTC, lilin90 commented on maintain-tidb-using-tiup.md
> +- Clean up the logs and data of all services except the node `172.16.13.12`:
```suggestion
- Clean up the logs and data of all services except the `172.16.13.12` node:
```

2020-08-27 11:31 UTC, lilin90 approved these changes
LGTM

2020-08-27 11:31 UTC, merged