benchmark: add description to explain the non-index test result
pingcap/docs pull request #5032
Opened 2021-03-12 10:08 UTC by TomShawn

### What is changed, added or deleted? (Required)

+ benchmark: add description to explain the non-index test result
+ Fix a typo: Region Group --> Raft Group

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/5719 https://github.com/pingcap/docs-cn/pull/5689
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-03-12 10:11 UTC, TomShawn commented
/translation from-docs-cn
/size small
/cc CharLotteiu Joyinqin
/status PTAL

2021-03-12 10:12 UTC, TomShawn commented
/label needs-cherry-pick-4.0

2021-03-12 10:12 UTC, TomShawn commented
/label needs-cherry-pick-5.0

2021-03-15 03:07 UTC, CharLotteiu approved these changes
rest LGTM

2021-03-15 03:07 UTC, CharLotteiu commented on benchmark/v4.0-performance-benchmarking-with-tpch.md
> +> The tables on which SQL statements are executed in this test only has the primary key and does not have secondary index. Therefore, the test result below is not influenced by index.
```suggestion
> The tables on which SQL statements are executed in this test only have primary keys and do not have secondary indexes. Therefore, the test result below is not influenced by indexes.
```

2021-03-15 03:10 UTC, Joyinqin requested changes

2021-03-15 03:10 UTC, Joyinqin commented on benchmark/v4.0-performance-benchmarking-with-tpch.md
> +> The tables on which SQL statements are executed in this test only has the primary key and does not have secondary index. Therefore, the test result below is not influenced by index.
> In this test, the tables on which SQL statements are executed only have the primary keys and do not have secondary indexes. Therefore, the test result below is not influenced by the index.

2021-03-15 03:14 UTC, Joyinqin approved these changes
rest LGTM

2021-03-15 03:46 UTC, TomShawn commented
@CharLotteiu PTAL again, thanks!

2021-03-15 05:59 UTC, TomShawn commented
/merge

2021-03-16 08:29 UTC, CharLotteiu commented
/lgtm

2021-03-16 08:30 UTC, TomShawn commented
/merge

2021-03-16 08:30 UTC, merged