Remove contents about PiTR feature
pingcap/docs pull request #5879
Opened 2021-06-29 02:18 UTC by IANTHEREAL

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
The PiTR function an experiment in 2020 and there is no follow-up test and work, not recommanded to customer, even in PoC. 
It should be better to remove now, and add it back when it's ready

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-06-29 02:23 UTC, IANTHEREAL commented
@Ishiihara @qiancai @3pointer  PTAL

2021-06-29 02:37 UTC, TomShawn commented
@

> @Ishiihara @qiancai @3pointer PTAL

@dveeden is the author of the doc content.

2021-06-29 02:56 UTC, 3pointer approved these changes

2021-06-29 04:43 UTC, dveeden requested changes
I think that adding a warning in the docs instead is better.

I don't think removing it completely is a good step. At least we should leave some info about this being an experimental feature. Maybe also add info about what people should use instead (TiDB Binlog?).

2021-06-29 06:27 UTC, IANTHEREAL commented
@dveeden Got you point. Actually I am quite confused about the standard of the experimental function. This feature is initially developed and has not undergone any testing, whether development or QA verification, so I think it is not suitable for release as an experimental feature. 

And for the PiTR feature, I think it is currently not supported now, and there is no suitable alternative, such as the tidb binlog you mentioned. I think we need to advance this feature as soon as possible

The above point of view is mainly based on the fact that we don’t want users to use a feature that is full of problems and may be changed.

2021-06-29 07:13 UTC, dveeden commented
@IANTHEREAL I do think people are using TiDB Binlog for this. There is no mention of this being experimental or deprecated on https://docs.pingcap.com/tidb/stable/tidb-binlog-reparo

For now adding a warning to TiCDC PITR similar to this https://docs.pingcap.com/tidb/stable/use-br-command-line-tool#back-up-raw-kv-experimental-feature would be good.

I agree that testing and removing the experimental flag of this feature would be good.

2021-06-29 07:42 UTC, IANTHEREAL commented
@dveeden Ok, Let me see

2021-07-01 08:19 UTC, IANTHEREAL commented
@dveeden Sorry for the late reply, I have been on a business trip in the last two days. I think we have a deviation from the standard definition of the experimental feature. After all, it has not been tested and is not recommended for any users. If you want to keep these contents, how about we put it in a file separately, in this file we can also describe the use of tidb binlog as an alternative solution

2021-07-01 08:36 UTC, dveeden commented
@IANTHEREAL I'm ok with that.

2021-07-15 06:56 UTC, TomShawn commented
@IANTHEREAL @dveeden Any update?

2021-07-15 08:43 UTC, dveeden commented
@TomShawn No updates from me, I'm waiting for @IANTHEREAL to update this PR

2022-02-09 11:11 UTC, closed without merging