tidb replica read support global set.
pingcap/docs pull request #7641
Opened 2022-02-17 13:05 UTC by tier-cap

Signed-off-by: tier-cap <zhengxiaojin@pingcap.com>

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

tidb replica read support global set.
### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions](https://github.com/pingcap/docs/blob/master/CONTRIBUTING.md#guideline-for-choosing-the-affected-versions).

- [ ] master (the latest development version)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-cn/pull/8422
- Other reference link(s): 
https://github.com/pingcap/docs/pull/6451/files
https://github.com/pingcap/tidb/pull/27622

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-02-18 03:15 UTC, xhebox approved these changes

2022-02-18 05:22 UTC, en-jin19 commented on follower-read.md
>  {{< copyable "sql" >}}
@tier-cap please update line 21 from "To enable TiDB's Follower Read feature, modify the value of the `tidb_replica_read` session variable:" to "To enable TiDB's Follower Read feature, modify the value of the `tidb_replica_read` variable:"

2022-02-18 05:22 UTC, en-jin19 requested changes
line 21 is to be changed to remove "session"

2022-02-18 07:19 UTC, NingLin-P approved these changes

2022-02-21 05:25 UTC, en-jin19 commented on follower-read.md
> +To enable TiDB's Follower Read feature, modify the value of the `tidb_replica_read` variable:
```suggestion
To enable TiDB's Follower Read feature, modify the value of the `tidb_replica_read` variable to `follower` or `leader-and-follower`:
```

2022-02-21 05:25 UTC, en-jin19 commented on follower-read.md
> +This variable is used to set the data read mode.
```suggestion
This variable is used to set the expected data read mode.
```

2022-02-22 11:17 UTC, en-jin19 approved these changes
LGTM

2022-02-22 11:18 UTC, en-jin19 commented
/merge

2022-02-22 11:31 UTC, merged